name: "Feature Request"
description: "Propose a new feature or enhancement for the project."
labels: 
  - "feature"
projects: ["SideQuest/1"]
assignees:
  - amltms
body:
  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "Describe the feature in detail. What problem does it solve? How will it improve the project?"
      placeholder: "Describe your feature request"
  - type: textarea
    id: use-case
    attributes:
      label: "Use Case"
      description: "Explain the use case for this feature. Who will use it and how?"
      placeholder: "Explain the use case"
  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level"
      description: "Indicate the importance of this feature."
      options:
        - "Low"
        - "Medium"
        - "High"
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots related to your request."
      placeholder: "Provide additional context"
